name: 'Notifier'
description: 'Notifies to Slack when Bandit issues are found'
inputs:
  input-file:
    description: 'file with message contents'
    required: true
  message-type:
    description: "type of message e.g. 'slack'"
    required: true
  slack-token:
    description: 'slack token'
    required: false
    default: '""'
  slack-channel:
    description: 'slack target channel'
    required: false
    default: '""'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.message-type }}
    - ${{ inputs.slack-token }}
    - ${{ inputs.slack-channel }}
    - ${{ inputs.input-file }}
